hw_10_dj/hw_10_django/hw_10_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    # path("users/", include("users.urls")),
]

hw_10_dj/hw_10_django/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page_number>", views.main, name="root_paginate"),
]

hw_10_dj/hw_10_django/quotes/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=50)
    discription = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    # def __str__(self):
    #     return self.fullname
    
class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)
    
    # def __str__(self):
    #     return self.name    
    
class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE,default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    # def __str__(self):
    #     return self.quote[:20]
    

hw_10_dj/hw_10_django/users/models.py
from django.db import models

# Create your models here.

hw_10_dj/hw_10_django/quotes/views.py
from django.shortcuts import render
from django.core.paginator import Paginator

# Create your views here.
from .utils import get_mongodb

def main(request, page_number=1):
    db = get_mongodb()
    quotes = db.qoutes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page_number)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})

hw_10_dj/hw_10_django/users/views.py
from django.shortcuts import render

# Create your views here.

hw_10_dj/hw_10_django/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title> HW_10 </title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    <a href="/login" class="btn btn-primary">SignUp</a>
                    <a href="/login" class="btn btn-primary">Login</a>
                    <a href="/login" class="btn btn-primary">Logout</a>
                </p>
            </div>
        </div>
    
    
        {% block content %} {% endblock %}
    
    </div>
</body>
</html>

hw_10_dj/hw_10_django/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}

        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{ quote.quote }}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
                <a href="/author/{{quote.author}}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags %}
                <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
                {% endfor %}

            </div>
        </div>

        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class= {% if not quotes.has_previos %} disabled {% endif %}
                    href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %}  {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>

                <li class="next">
                    <a class= {% if not quotes.has_next %} disabled {% endif %}
                    href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %}  {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>

            
        </nav>
    </div>
        
    
        </div>
</div>


{% endblock %}